import pathlib, os
URL_TEST = (pathlib.Path(__file__).resolve().parent.parent / "out" / "test.html").as_uri()
os.makedirs("shots", exist_ok=True)
import sys
from playwright.sync_api import sync_playwright
P = sys.argv[1] if len(sys.argv) > 1 else "d1"
URL = URL_TEST; errs = []
def wait_agent(pg):
    pg.wait_for_timeout(150); pg.wait_for_function("() => !document.querySelector('#agent .typing')", timeout=8000); pg.wait_for_timeout(100)
with sync_playwright() as p:
    b = p.chromium.launch()
    pg = b.new_page(viewport={"width": 1280, "height": 860})
    pg.on("pageerror", lambda e: errs.append(str(e)))
    pg.goto(URL); pg.wait_for_timeout(900)
    pg.screenshot(path=f"shots/{P}-1-cover.png")
    pg.click("#entryForm button[type=submit]"); pg.click("[data-act=course-open][data-id=info]"); pg.click("#goLesson"); pg.click("[data-act=notice-next]"); pg.wait_for_timeout(150)
    pg.screenshot(path=f"shots/{P}-2-choose.png")
    pg.click("label.choice >> nth=1"); pg.click("[data-act=choose-start]"); pg.wait_for_timeout(300)
    pg.click("[data-act=toc-seg][data-i='2']"); pg.wait_for_timeout(300)
    pg.click("#agent .chip >> nth=0"); wait_agent(pg)
    pg.fill("#chatIn", "끝값은 안 들어가서 1, 2, 3, 4니까 네 번이야"); pg.press("#chatIn", "Enter"); wait_agent(pg)
    pg.screenshot(path=f"shots/{P}-3-learn1.png")
    pg.click("[data-act=toc-seg][data-i='3']"); pg.wait_for_timeout(200)
    for _ in range(5): pg.click("[data-act=trace-step]")
    pg.evaluate("window.scrollTo(0, 420)"); pg.wait_for_timeout(100)
    pg.screenshot(path=f"shots/{P}-4-learn2.png")
    pg.click("[data-act=toc-seg][data-i='5']"); pg.click("[data-act=to-check]"); pg.wait_for_timeout(250)
    pg.click("input[data-opt=c1][value=c]", force=True); wait_agent(pg)
    pg.click("[data-act=check-submit]"); pg.wait_for_timeout(200)
    pg.evaluate("window.scrollTo(0, 300)"); pg.wait_for_timeout(100)
    pg.screenshot(path=f"shots/{P}-5-check.png")
    pg.click("[data-act=lab-toggle]"); pg.wait_for_timeout(200)
    pg.click("[data-act=lab-run]"); pg.wait_for_function("() => !/불러오는|실행하는/.test(document.querySelector('#codeOut').textContent)", timeout=30000)
    pg.locator("#codeLab").scroll_into_view_if_needed(); pg.evaluate("window.scrollBy(0, -60)"); pg.wait_for_timeout(100)
    pg.screenshot(path=f"shots/{P}-6-codelab.png")
    # 형성평가, 오답 노트
    pg.evaluate("window.scrollTo(0,0)")
    for iid, v in [("c1","b")]: pg.click(f"input[data-opt={iid}][value={v}]", force=True); pg.click("[data-act=check-submit]")
    pg.click("[data-act=check-next]"); pg.click("input[data-opt=c2][value=b]", force=True); pg.click("[data-act=check-submit]")
    pg.click("[data-act=check-next]"); pg.click("input[data-opt=c3][value=b]", force=True); pg.click("[data-act=check-submit]")
    pg.click("[data-act=to-formative]"); pg.wait_for_timeout(150); pg.click("[data-act=modal-ok]"); pg.wait_for_timeout(250)
    pg.click("input[data-opt=f1][value=b]", force=True)
    pg.screenshot(path=f"shots/{P}-7-formative.png")
    for i, (iid, v) in enumerate([("f1","b"),("f2","b"),("f3","a"),("f4","a")]):
        pg.click(f"input[data-opt={iid}][value={v}]", force=True); pg.click("[data-act=form-next]"); pg.wait_for_timeout(60)
    pg.fill("input[data-short=f5]", "10"); pg.click("[data-act=form-finish]"); pg.click("input[data-est][value='4']")
    pg.click("[data-act=form-submit]"); pg.wait_for_timeout(120); pg.click("[data-act=modal-ok]"); pg.wait_for_timeout(250)
    pg.click("[data-act=note-retry][data-id=f3]"); pg.click("input[data-retry=f3][value=b]", force=True); pg.click("[data-act=note-retry-submit][data-id=f3]"); pg.wait_for_timeout(150)
    pg.screenshot(path=f"shots/{P}-8-note.png")
    pg.click("#toc [data-act=toc-form][data-i='2']"); pg.wait_for_timeout(200); pg.screenshot(path=f"shots/{P}-8b-review-form.png")
    pg.click("#toc [data-act=toc-check][data-i='0']"); pg.wait_for_timeout(200); pg.screenshot(path=f"shots/{P}-8c-review-check.png")
    pg.click(".review-bar [data-act=review-end]"); pg.wait_for_timeout(150)
    pg.click("#endBtn"); pg.wait_for_timeout(200); pg.screenshot(path=f"shots/{P}-8d-dash-note.png", full_page=True)
    pg.click("#goLesson"); pg.wait_for_timeout(200)
    pg.emulate_media(color_scheme="dark"); pg.evaluate("window.scrollTo(0,0)"); pg.wait_for_timeout(150)
    pg.screenshot(path=f"shots/{P}-9-note-dark.png")
    m = b.new_page(viewport={"width": 390, "height": 844}, device_scale_factor=2, is_mobile=True, has_touch=True)
    m.on("pageerror", lambda e: errs.append(str(e)))
    m.goto(URL); m.wait_for_timeout(700)
    m.click("#entryForm button[type=submit]"); m.click("[data-act=course-open][data-id=info]"); m.click("#goLesson"); m.click("[data-act=notice-next]"); m.click("label.choice >> nth=2"); m.click("[data-act=choose-start]"); m.wait_for_timeout(250)
    m.click("[data-act=seg-go][data-i='2']"); m.wait_for_timeout(250)
    m.screenshot(path=f"shots/{P}-m1-learn.png")
    m.click("#agentFab"); m.wait_for_timeout(350)
    m.screenshot(path=f"shots/{P}-m2-sheet.png")
    print("mobile sw", m.evaluate("document.documentElement.scrollWidth"))
    b.close()
print("ERRS", errs)
