import pathlib, os
URL_TEST = (pathlib.Path(__file__).resolve().parent.parent / "out" / "test.html").as_uri()
os.makedirs("shots", exist_ok=True)
from playwright.sync_api import sync_playwright
errs=[]
U=URL_TEST
with sync_playwright() as p:
    b=p.chromium.launch(); pg=b.new_page(viewport={"width":1440,"height":900})
    pg.on("pageerror", lambda e: errs.append(str(e)))
    pg.goto(U); pg.wait_for_timeout(700)
    pg.screenshot(path="shots/k0-login.png")
    pg.click("#entryForm button[type=submit]"); pg.wait_for_timeout(250)
    pg.screenshot(path="shots/k1-hub.png", full_page=True)
    pg.click("[data-act=course-open][data-id=info]"); pg.wait_for_timeout(250)
    pg.screenshot(path="shots/k2-dash-new.png", full_page=True)
    print("task btn disabled:", pg.is_disabled(".tc-acts button:has-text('과제 제출하러 가기')"))
    pg.click("#goLesson"); pg.click("[data-act=notice-next]"); pg.click("label.choice >> nth=1"); pg.click("[data-act=choose-start]"); pg.wait_for_timeout(300)
    pg.click("[data-act=toc-seg][data-i='2']"); pg.wait_for_timeout(250)
    pg.click("#toolRail [data-v=memo]"); pg.fill("#memoTa","range 끝값은 안 들어간다"); pg.click("#toolPane [data-act=memo-save]"); pg.wait_for_timeout(150)
    pg.click("[data-act=toc-seg][data-i='4']"); pg.wait_for_timeout(250)
    pg.click("#toolRail [data-v=memo]") if pg.locator("#toolRail [data-v=memo].on").count()==0 else None
    pg.fill("#memoTa","빈칸은 % 3 == 0"); pg.click("#toolPane [data-act=memo-save]"); pg.wait_for_timeout(150)
    pg.screenshot(path="shots/k3-memo-pane.png")
    pg.click("#endBtn"); pg.wait_for_timeout(250)
    pg.screenshot(path="shots/k4-dash-progress.png", full_page=True)
    pg.click(".side-item[data-p=memo]"); pg.wait_for_timeout(200); pg.screenshot(path="shots/k5-memo-page.png", full_page=True)
    pg.click("[data-act=note-go] >> nth=1"); pg.wait_for_timeout(300)
    print("after jump seg:", pg.text_content("#segTitle"))
    pg.screenshot(path="shots/k6-jumped.png")
    # 확인 문항 단계로 가서 다시 보기
    pg.click("[data-act=toc-seg][data-i='5']"); pg.click("[data-act=to-check]"); pg.wait_for_timeout(250)
    pg.click("[data-act=toc-seg][data-i='2']"); pg.wait_for_timeout(250)
    print("review:", pg.locator(".review-bar").count(), pg.text_content("#segTitle"))
    pg.screenshot(path="shots/k7-review.png")
    pg.click(".review-bar [data-act=review-end]"); pg.wait_for_timeout(200)
    print("back stage:", pg.evaluate("document.querySelector('#lessonInner').dataset.stage"))
    # 진척도에서 완료한 곳 다시 보기(확인 문항 단계: 학습 구간 완료)
    pg.click("#endBtn"); pg.wait_for_timeout(200)
    pg.screenshot(path="shots/k4b-dash-check.png", full_page=True)
    pg.click(".pg-rows [data-act=review-open][data-k=seg]"); pg.wait_for_timeout(250)
    print("review from dash:", pg.locator(".review-bar").count(), pg.text_content("#segTitle"))
    pg.click(".review-bar [data-act=review-end]"); pg.wait_for_timeout(150)
    # 게시판
    pg.click("#endBtn"); pg.click(".side-item[data-p=board]"); pg.wait_for_timeout(200)
    pg.screenshot(path="shots/k8-board.png", full_page=True)
    pg.click("[data-act=post-view][data-id=t3]"); pg.wait_for_timeout(150)
    pg.screenshot(path="shots/k9a-vote-before.png", full_page=True)
    pg.click("label.vote-opt >> nth=1"); pg.click("[data-act=vote-cast]"); pg.wait_for_timeout(150)
    pg.screenshot(path="shots/k9-vote.png", full_page=True)
    pg.click("[data-act=board-list]"); pg.click("[data-act=post-view][data-id=t5]"); pg.wait_for_timeout(150)
    pg.screenshot(path="shots/k9b-ladder-before.png", full_page=True)
    pg.click(".lad-p >> nth=2"); pg.wait_for_timeout(1600)
    pg.screenshot(path="shots/k9c-ladder-one.png", full_page=True)
    pg.click("[data-act=lad-all]"); pg.wait_for_timeout(1700)
    pg.screenshot(path="shots/k9d-ladder-all.png", full_page=True)
    pg.click("[data-act=board-list]"); pg.click("[data-act=post-view][data-id=t4]"); pg.wait_for_timeout(150)
    pg.screenshot(path="shots/k9e-draw-teacher.png", full_page=True)
    pg.click("[data-act=board-list]"); pg.click(".bsec-h [data-act=post-write]"); pg.wait_for_timeout(150)
    pg.fill("#pTitle","실행 화면 올려요"); pg.fill("#pBody","3의 배수 출력 화면이에요."); pg.set_input_files("#pFile",str(pathlib.Path(__file__).resolve().parent / "fixtures" / "run.png")); pg.click("#postForm button[type=submit]"); pg.wait_for_timeout(400)
    pg.screenshot(path="shots/k10-post-file.png", full_page=True)
    pg.click("[data-act=board-list]"); pg.click(".bsec-h [data-act=post-write]"); pg.wait_for_timeout(150)
    pg.click(".ptype label:has-text('제비뽑기')"); pg.wait_for_timeout(100)
    pg.fill("#pTitle","모둠 역할 뽑기"); pg.fill("#pCands","기록\n발표\n코딩\n시간 관리\n자료 찾기\n정리"); pg.fill("#pN","2"); pg.click("#postForm button[type=submit]"); pg.wait_for_timeout(300)
    pg.screenshot(path="shots/k11-draw-new.png", full_page=True)
    pg.click("[data-act=slip-shuffle]"); pg.wait_for_timeout(1000)
    pg.click(".slip >> nth=1"); pg.wait_for_timeout(700)
    pg.screenshot(path="shots/k11b-draw-one.png", full_page=True)
    pg.click(".slip >> nth=4"); pg.wait_for_timeout(1200)
    pg.screenshot(path="shots/k12-draw.png", full_page=True)
    pg.click("[data-act=slip-all]"); pg.wait_for_timeout(700); pg.screenshot(path="shots/k12b-draw-all.png", full_page=True)
    pg.click("[data-act=board-list]"); pg.click(".bsec-h [data-act=post-write]"); pg.click(".ptype label:has-text('사다리타기')")
    pg.fill("#pTitle","발표 순서 사다리"); pg.fill("#pPlayers","가\n나\n다\n라"); pg.fill("#pResults","첫째\n둘째"); pg.click("#postForm button[type=submit]"); pg.wait_for_timeout(300)
    pg.screenshot(path="shots/k12c-ladder-new.png", full_page=True)
    pg.click("[data-act=board-list]"); pg.click(".bsec-h [data-act=post-write]"); pg.click(".ptype label:has-text('투표')")
    pg.fill("#pTitle","점심 뭐 먹지"); pg.fill("#pOpt0","짜장"); pg.click("#postForm button[type=submit]"); pg.wait_for_timeout(150)
    print("vote err:", pg.text_content("#postErr"))
    pg.fill("#pOpt1","짬뽕"); pg.fill("#pOpt2","볶음밥"); pg.check("#pMulti"); pg.click("#postForm button[type=submit]"); pg.wait_for_timeout(200)
    pg.screenshot(path="shots/k12d-vote-multi.png", full_page=True)
    pg.click("[data-act=board-list]"); pg.wait_for_timeout(150); pg.screenshot(path="shots/k13-board-after.png", full_page=True)
    # 교사: 과제 내기
    pg.click("[data-act=research-open]"); pg.fill("#rgCode","0000"); pg.click("#researchGate button[type=submit]"); print("gate err:", pg.text_content("#rgErr")); pg.fill("#rgCode","0650"); pg.click("#researchGate button[type=submit]"); pg.click("#tab-classes"); pg.wait_for_timeout(200)
    pg.screenshot(path="shots/k14-drawer-classes.png")
    pg.click("#taskNewForm button[type=submit]"); pg.wait_for_timeout(150)
    pg.fill("#cSubject","영어"); pg.fill("#cTeacher","이수민"); pg.select_option("#cD0","2"); pg.select_option("#cP0","4"); pg.click("#courseForm button[type=submit]"); pg.wait_for_timeout(150)
    pg.fill("#nTitle","내일은 컴퓨터실에서 수업해요"); pg.fill("#nBody","3교시에 컴퓨터실로 모여요."); pg.click("#noticeForm button[type=submit]"); pg.wait_for_timeout(150)
    pg.click("[data-act=drawer-close] >> nth=1"); pg.wait_for_timeout(150)
    pg.click(".side-item[data-p=dash]"); pg.wait_for_timeout(200)
    print("task btn disabled now:", pg.is_disabled(".tc-acts button:has-text('과제 제출하러 가기')"))
    pg.screenshot(path="shots/k15-dash-task.png", full_page=True)
    pg.click(".tc-acts button:has-text('과제 제출하러 가기')"); pg.wait_for_timeout(200)
    pg.fill("#kText","for i in range(1, 31):\n    if i % 3 == 0:\n        print(i)"); pg.set_input_files("#kFile",str(pathlib.Path(__file__).resolve().parent / "fixtures" / "x.txt")); pg.click("#taskForm button[type=submit]"); pg.wait_for_timeout(300)
    pg.screenshot(path="shots/k16-task-done.png", full_page=True)
    pg.click("[data-act=hub-open]"); pg.wait_for_timeout(200); pg.screenshot(path="shots/k17-hub-3.png", full_page=True)
    pg.click("[data-act=course-open][data-id=math]"); pg.wait_for_timeout(200); pg.screenshot(path="shots/k18-math-dash.png", full_page=True)
    pg.emulate_media(color_scheme="dark"); pg.click("[data-act=hub-open]"); pg.click("[data-act=course-open][data-id=info]"); pg.wait_for_timeout(200); pg.screenshot(path="shots/k19-dash-dark.png", full_page=True)
    m=b.new_page(viewport={"width":390,"height":844}, device_scale_factor=2, is_mobile=True, has_touch=True)
    m.on("pageerror", lambda e: errs.append(str(e)))
    m.goto(U); m.wait_for_timeout(600); m.screenshot(path="shots/k20-m-login.png")
    m.click("#entryForm button[type=submit]"); m.wait_for_timeout(200); m.screenshot(path="shots/k21-m-hub.png", full_page=True)
    m.click("[data-act=course-open][data-id=info]"); m.wait_for_timeout(200); m.screenshot(path="shots/k22-m-dash.png", full_page=True)
    print("m sw", m.evaluate("document.documentElement.scrollWidth"))
    m.click("#goLesson"); m.click("[data-act=notice-next]"); m.click("label.choice >> nth=2"); m.click("[data-act=choose-start]"); m.wait_for_timeout(250)
    m.click("[data-act=memo-open]"); m.wait_for_timeout(200); m.screenshot(path="shots/k23-m-memo.png")
    print("m sw2", m.evaluate("document.documentElement.scrollWidth"))
    b.close()
print("ERRS", errs)
