import pathlib, os
URL_TEST = (pathlib.Path(__file__).resolve().parent.parent / "out" / "test.html").as_uri()
os.makedirs("shots", exist_ok=True)
import os, json, time
from playwright.sync_api import sync_playwright

OUT = "/home/claude/proto/shots"
os.makedirs(OUT, exist_ok=True)
URL = URL_TEST
errors = []

def attach(page, tag):
    page.on("console", lambda m: errors.append(f"[{tag}] console.{m.type}: {m.text}") if m.type in ("error", "warning") else None)
    page.on("pageerror", lambda e: errors.append(f"[{tag}] pageerror: {e}"))

def wait_agent(page, t=8000):
    page.wait_for_timeout(150)
    page.wait_for_function("() => !document.querySelector('#agent .typing')", timeout=t)
    page.wait_for_timeout(120)

def shot(page, name, full=False):
    page.screenshot(path=f"{OUT}/{name}.png", full_page=full)

def chip(page, label):
    page.click(f"#agent .chip[data-label='{label}']")
    wait_agent(page)

def say(page, text):
    page.fill("#chatIn", text)
    page.press("#chatIn", "Enter")
    wait_agent(page)

with sync_playwright() as p:
    b = p.chromium.launch()
    ctx = b.new_context(viewport={"width": 1280, "height": 860}, locale="ko-KR")
    page = ctx.new_page(); attach(page, "desktop")
    page.goto(URL); page.wait_for_timeout(1200)
    shot(page, "01-cover")
    page.click("#entryForm button[type=submit]"); page.click("[data-act=course-open][data-id=info]"); page.click("#goLesson"); page.wait_for_timeout(200)
    shot(page, "02-notice")
    page.click("[data-act=notice-next]"); page.wait_for_timeout(200)
    shot(page, "03-choose")
    page.click("label.choice >> nth=1"); page.click("[data-act=choose-start]"); page.wait_for_timeout(300)
    shot(page, "04-learn-goal")
    page.click("[data-act=seg-next]"); page.fill("#thinkTa", "수를 차례로 센다. 3의 배수인지 본다."); page.click("[data-act=think-reveal]"); page.wait_for_timeout(200)
    shot(page, "05-think")
    page.click("[data-act=seg-next]"); page.wait_for_timeout(300)
    page.fill("#labEnd", "7"); page.wait_for_timeout(200)
    chip(page, "이게 무슨 뜻이야?")
    say(page, "끝값은 안 들어가서 1, 2, 3, 4니까 네 번이야")
    shot(page, "06-learn1")
    page.click("[data-act=seg-next]"); page.wait_for_timeout(300)
    for _ in range(4): page.click("[data-act=trace-step]")
    shot(page, "07-learn2")
    say(page, "%는 나머지야. 7 % 3은 1이야")
    page.click("[data-act=seg-next]"); page.wait_for_timeout(200)
    page.fill("#actA", "1"); page.fill("#actB", "20"); page.fill("#actC", "4"); page.click("[data-act=act-run]"); page.wait_for_timeout(150)
    shot(page, "08-activity-wrong")
    page.fill("#actB", "21"); page.click("[data-act=act-run]"); page.wait_for_timeout(150)
    shot(page, "09-activity-ok")
    page.click("[data-act=seg-next]"); page.wait_for_timeout(200)
    page.click("input[data-self=sc1] >> nth=0"); page.click("input[data-self=sc2] >> nth=1"); page.click("input[data-self=sc3] >> nth=2")
    shot(page, "10-summary", full=True)
    page.click("[data-act=to-check]"); page.wait_for_timeout(300)
    # c1: 메이트와 같은 오답을 고른 뒤 도움 요청, 제출, 다시 제출
    page.click("input[data-opt=c1][value=c]", force=True); page.wait_for_timeout(300)
    chip(page, "내 답 맞는지 봐 줘")
    page.click("[data-act=check-submit]"); page.wait_for_timeout(200)
    shot(page, "11-check-wrong")
    say(page, "7은 포함 안 되니까 5번 아니야?")
    page.click("input[data-opt=c1][value=b]", force=True); page.click("[data-act=check-submit]"); page.wait_for_timeout(200)
    shot(page, "12-check-right")
    page.click("[data-act=check-next]"); page.wait_for_timeout(200)
    page.click("input[data-opt=c2][value=b]", force=True); page.click("[data-act=check-submit]")
    page.click("[data-act=check-next]"); page.wait_for_timeout(200)
    page.click("input[data-opt=c3][value=a]", force=True); page.wait_for_timeout(300)
    say(page, "나머지를 봐야 하니까 %를 써야 할 것 같아")
    page.click("input[data-opt=c3][value=b]", force=True); page.click("[data-act=check-submit]"); page.wait_for_timeout(200)
    page.click("[data-act=to-formative]"); page.wait_for_timeout(200)
    shot(page, "13-modal")
    page.click("[data-act=modal-ok]"); page.wait_for_timeout(300)
    shot(page, "14-formative")
    answers = [("f1", "b"), ("f2", "b"), ("f3", "a"), ("f4", "a")]
    for i, (iid, v) in enumerate(answers):
        page.click(f"input[data-opt={iid}][value={v}]", force=True)
        if i == 1: page.click("input[data-conf=f2] >> nth=0")
        page.click("[data-act=form-next]"); page.wait_for_timeout(100)
    page.fill("input[data-short=f5]", "10")
    page.click("[data-act=form-finish]"); page.wait_for_timeout(150)
    page.click("input[data-est][value='4']")
    shot(page, "15-form-finish")
    page.click("[data-act=form-submit]"); page.wait_for_timeout(150); page.click("[data-act=modal-ok]"); page.wait_for_timeout(300)
    shot(page, "16-note", full=True)
    page.click("[data-act=note-retry][data-id=f3]"); page.wait_for_timeout(150)
    page.click("input[data-retry=f3][value=b]", force=True); page.click("[data-act=note-retry-submit][data-id=f3]"); page.wait_for_timeout(150)
    page.click("[data-act=note-talk][data-id=f3]"); page.wait_for_timeout(150)
    chip(page, "왜 틀렸는지 같이 보자")
    page.click("input[data-report=c2] >> nth=0")
    shot(page, "17-note-after")
    page.click("[data-act=to-done]"); page.wait_for_timeout(300)
    page.click("input[data-manip=m1] >> nth=1"); page.click("input[data-manip=m2] >> nth=0")
    shot(page, "18-done")
    page.click(".top-actions [data-act=research-open]"); page.fill("#rgCode","0650"); page.click("#researchGate button[type=submit]"); page.wait_for_timeout(200)
    shot(page, "19-drawer-settings")
    for tab in ["harness", "logs", "summary"]:
        page.click(f"[data-act=tab][data-tab={tab}]"); page.wait_for_timeout(150)
        shot(page, f"20-drawer-{tab}")
    # 러닝코치 조건으로 새로 시작
    page.click("[data-act=tab][data-tab=settings]"); page.wait_for_timeout(100)
    page.click("[data-act=set][data-k=condition][data-v=coach]"); page.wait_for_timeout(100)
    page.click("[data-act=restart-cond]"); page.wait_for_timeout(150); page.click("[data-act=modal-ok]"); page.wait_for_timeout(200)
    page.click("button.drawer-close"); page.wait_for_timeout(100)
    page.click("[data-act=notice-next]"); page.wait_for_timeout(150)
    shot(page, "21-coach-choose")
    page.click("[data-act=choose-start]"); page.wait_for_timeout(200)
    page.click("[data-act=toc-seg][data-i='2']"); page.wait_for_timeout(200)
    chip(page, "이게 무슨 뜻이야?")
    say(page, "그럼 range(1, 5)는 네 번이야?")
    shot(page, "22-coach-learn1")
    page.click("[data-act=toc-seg][data-i='5']"); page.click("[data-act=to-check]"); page.wait_for_timeout(200)
    chip(page, "어떻게 시작하지?")
    page.click("input[data-opt=c1][value=c]", force=True); page.wait_for_timeout(200)
    chip(page, "내 답 맞는지 봐 줘")
    shot(page, "23-coach-check")
    page.emulate_media(color_scheme="dark"); page.wait_for_timeout(200)
    shot(page, "24-dark")
    page.emulate_media(color_scheme="light")
    page.click(".top-actions [data-act=view-open]"); page.wait_for_timeout(150)
    page.click("[data-act=view-set][data-k=size][data-v=l]"); page.wait_for_timeout(150)
    shot(page, "25-view-modal")
    page.keyboard.press("Escape")
    state = page.evaluate("() => { const k = Object.keys(localStorage).find(x => x.includes(':s:')); const s = JSON.parse(localStorage.getItem(k)); return {stage: s.stage, cond: s.condition, logs: s.logs.length, chat: s.chat.length}; }")
    print("STATE", json.dumps(state, ensure_ascii=False))
    ctx.close()

    # 좁은 화면
    m = b.new_context(viewport={"width": 390, "height": 844}, locale="ko-KR", device_scale_factor=2, is_mobile=True, has_touch=True)
    mp = m.new_page(); attach(mp, "mobile")
    mp.goto(URL); mp.wait_for_timeout(1000)
    shot(mp, "30-m-cover")
    mp.click("#entryForm button[type=submit]"); mp.click("[data-act=course-open][data-id=info]"); mp.click("#goLesson"); mp.click("[data-act=notice-next]"); mp.click("label.choice >> nth=2"); mp.click("[data-act=choose-start]"); mp.wait_for_timeout(300)
    mp.click("[data-act=seg-go][data-i='2']"); mp.wait_for_timeout(300)
    shot(mp, "31-m-learn1")
    mp.click("#agentFab"); mp.wait_for_timeout(400)
    shot(mp, "32-m-sheet")
    sw = mp.evaluate("() => document.documentElement.scrollWidth")
    print("mobile scrollWidth", sw)
    m.close()
    b.close()

print("ERRORS", len(errors))
for e in errors[:40]: print(e)
